



CREATE TABLE Conta(
Id_Conta INTEGER PRIMARY KEY,
Nome_Cliente VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL,
Saldo DECIMAL(10,2) NOT NULL,
DataCriacao DATETIME NOT NULL
);

CREATE TABLE Transacao(
ID_Transacao INTEGER PRIMARY KEY,
ID_Conta_Origem INTEGER NOT NULL,
ID_Conta_Destino INTEGER NOT NULL,
Valor DECIMAL(10,2) NOT NULL,
DataTransacao DATETIME NOT NULL,
FOREIGN KEY(ID_Conta_Origem) REFERENCES Conta(Id_Conta),
FOREIGN KEY(ID_Conta_Destino) REFERENCES Conta(Id_Conta)
);

CREATE TABLE Emprestimo(
ID_Emprestimo INTEGER PRIMARY KEY,
ID_Conta INTEGER NOT NULL,
Valor DECIMAL(10,2) NOT NULL,
DataEmprestimo DATETIME NOT NULL,
Juros DECIMAL(10,2) NOT NULL,
Prazo INTEGER NOT NULL,
FOREIGN KEY(ID_Conta) REFERENCES Conta(Id_Conta)
);

CREATE TABLE CartaoCredito(
ID_Cartao INTEGER PRIMARY KEY,
ID_Conta INTEGER NOT NULL,
Limite DECIMAL(10,2) NOT NULL,
DataAprovacao DATETIME NOT NULL,
FaturaAtual DECIMAL(10,2) NOT NULL,
FOREIGN KEY(ID_Conta) REFERENCES Conta(Id_Conta)
);

CREATE TABLE PagamentoServiços(
ID_PagamentoServicos INTEGER PRIMARY KEY,
ID_Conta INTEGER NOT NULL,
Servico VARCHAR(50) NOT NULL,
Valor DECIMAL(10,2) NOT NULL,
DataPagamento DATETIME NOT NULL,
FOREIGN KEY(ID_Conta) REFERENCES Conta(Id_Conta)
);